### ISSUE TITLE
Install attempt errors with message about requiring vsphere-automation-sdk

### ISSUE THREAD

**Issue by akulbe** [chef/kitchen-vcenter#11]
### Versions:

* Version of kitchen-vcenter: attempting to install 1.2.0
* Version of test-kitchen: 1.16.0
* Version of chef: 1.6.2

### Platform Details

* Version of vCenter: VCSA
* Version of ESXi: 6.5.0u1

### Scenario:
Trying to install the kitchen-vcenter gem

### Steps to Reproduce:
chef gem install kitchen-vcenter

### Expected Result:
that the kitchen-vcenter gem would be installed

### Actual Result:
```
~/chef-repo-gci > chef gem install kitchen-vcenter
Fetching: socksify-1.7.1.gem (100%)
Successfully installed socksify-1.7.1
Fetching: httpi-2.4.2.gem (100%)
Successfully installed httpi-2.4.2
Fetching: wasabi-3.5.0.gem (100%)
Successfully installed wasabi-3.5.0
Fetching: akami-1.3.1.gem (100%)
Successfully installed akami-1.3.1
Fetching: savon-2.11.2.gem (100%)
Successfully installed savon-2.11.2
Fetching: kitchen-vcenter-1.2.0.gem (100%)
ERROR:  Error installing kitchen-vcenter:
	kitchen-vcenter requires vsphere-automation-sdk (~> 2.5)
```

**Comment by jjasghar** [comment]
You found an easter egg!

https://github.com/vmware/vsphere-automation-sdk-ruby/issues/10

You need to pull the code down and build it, we are going to be adding a "how-to" in the README note too soon.
