### ISSUE TITLE
Add support for linked clones

### ISSUE THREAD

**Issue by jmery** [chef/kitchen-vcenter#18]
### Versions:

* Version of kitchen-vcenter:
* Version of test-kitchen:
* Version of chef:

### Platform Details

* Version of vCenter:
* Version of ESXi:

### Scenario:
kitchen-vcenter should support the usage of linked clones so that creation of a new test kitchen instance doesn't take forever.  This is already implemented in rbvmomi so it should be easy to port over here.

**Comment by tas50** [comment]
Merged to master
