### ISSUE TITLE
Add supported vCenter version to Requirements

### ISSUE THREAD

**Issue by bioxcession** [chef/kitchen-vcenter#20]
Currently I'm not sure which vCenter versions are supported by this gem - I'm testing against 6.0, and I'm getting the following error:

    >>>>>>     Failed to complete #create action: [HTTP error (404)] on default-rhel7

I suspect it's due to my version of vCenter being unsupported, but I have no way to validate that suspicion without a list of supported versions.

**Comment by jjasghar** [comment]
Ah, we don’t have an explicit list but we do state:

> This is the official Chef test-kitchen plugin for VMware REST API. This plugin gives kitchen the ability to create, bootstrap, and test VMware vms.

If you have the REST API you should be supported.

**Comment by bioxcession** [comment]
Ah, fair enough. Could this be listed under the requirements section? I didn't infer the connection myself while looking through the readme.
