### ISSUE TITLE
Allow a network option

### ISSUE THREAD

**Issue by biox** [chef/kitchen-vcenter#21]
The chef-provisioning-vsphere driver supplies the following option:

```
network_name:
  - VLAN2071
```

If this was exposed as an option at both the driver level and the platform level I'd be elated. May work on this if I get some free time.

**Comment by tecracer-theinen** [comment]
Sorry, there was a bit of confusion on my side :)

Syntax is a bit different, as I implemented this for only one interface. But it should be close enough.
