### ISSUE TITLE
Qustion: How to shutdown/export provisioned VM?

### ISSUE THREAD

**Issue by nimDevOps** [chef/kitchen-vcenter#25]
### Versions:

* Version of kitchen-vcenter:
       kitchen-vcenter (1.2.1)
       rbvmomi (1.12.0)
* Version of test-kitchen:
       test-kitchen (1.20.0)
* Version of chef:
Chef Development Kit Version: 2.5.3
chef-client version: 13.8.5
berks version: 6.3.1
inspec version: 1.51.21

### Platform Details
* Version of vCenter:/ESXi:
6.5

### Scenario:

I use kitchen-vcenter driver to interact with VMware farm and provision VMs via test-kitchen .kitchen.yml file. Usual workflow is standard for test-kitchen
* kitchen create  suite-platform
* kitchen converge suite-platform
* kitchen verify suite-platform
* kitchen destroy suite-platform

When VM is provisioned (passed converge) and testcases passed (passed verify) it would be useful to shutdown VM and perform export. Export can be done via ovftool.exe utility provided by vmware, for example I use something like this:

ovftool.exe --shaAlgorithm=sha1 --noSSLVerify=true --skipManifestCheck --diskMode=thin --name=${suite_name}-${platform_name} -tt=ova vi://${user}:${password}@${ESXI_IP}/${vm_name} ${output}

The missing piece of the puzzle is actually VM shutdown. 
If there is a way to stop/shutdown VM using test-kitchen or I should use another tool like PowerCLI client from vmware?

**Comment by jjasghar** [comment]
At this time the `kitchen-vcenter` doesn't have this feature. I'd suggest do the `kitchen verify` then run a `PowerCLI` command to call the graceful shutdown then use `ovftool` to export it.

It's an interesting use case I'll give you that, but i'd imagine more people use `kitchen` to iterate, then the cookbook use something like `packer` to build the actual template.

Please reopen this if you have any more questions.
