### ISSUE TITLE
Driver requires a resource pool

### ISSUE THREAD

**Issue by tecracer-theinen** [chef/kitchen-vcenter#28]
### Versions:

* Version of kitchen-vcenter: 1.21.0
* Version of test-kitchen: 1.23.2

### Platform Details
* Version of vCenter: 6.7
* Version of ESXi: 6.5

### Scenario:
Trying to create a machine from TestKitchen on a VMWare host where no resource pools are defined. 

### Steps to Reproduce:
Create a TestKitchen configuration, not specifying a resource_pool and not having any defined on the target VMWare machine

### Expected Result:
Creation of a machine not in any VMWare resource pool OR stating that a resource pool is mandatory in kitchen execution/documentation

### Actual Result:
Testkitchen fails with a message about spec.pool being invalid, because the existence of a pool has been required after Issue #7 apparently.

Apparently, the code searches for the pool given or uses the first one in https://github.com/chef/kitchen-vcenter/blob/master/lib/kitchen/driver/vcenter.rb#L192

According to the VMWare documentation (which should apply to the used RbVmomi gem), the pool property is optional:
https://www.vmware.com/support/developer/converter-sdk/conv51_apireference/vim.vm.RelocateSpec.html

**Comment by tas50** [comment]
Fix merged to master
