### ISSUE TITLE
unable to search for templates in child folders 

### ISSUE THREAD

**Issue by smackmybitsup** [chef/kitchen-vcenter#29]
### Versions:

* Version of kitchen-vcenter: 1.2.1 
* Version of test-kitchen: 1.22.0
* Version of chef:  +13

### Platform Details

* Version of vCenter: 6.5
* Version of ESXi: 

### Scenario:
given the following configuration in .kitchen.yml
'''
platforms:
  - name: default
    driver_config:
            template: cent4kitchentmpl
      datacenter: "vCenterDC"
      folder: "kitchen"
'''
it would be nice to be able to use a template in a sub-folder. It appears the issue is because of a limitation in rbVmomi

### Actual Result:
templates that are not in the root are not found.

**Comment by tecracer-theinen** [comment]
Seconded, we ran into this in a workshop last week. Had to copy templates into the root, then it works.
