### ISSUE TITLE
HTTP error (404)

### ISSUE THREAD

**Issue by riponbanik** [chef/kitchen-vcenter#30]
### Versions:

* Version of kitchen-vcenter: v1.2.1
* Version of test-kitchen: v1.23.2
* Version of chef:3.2.30

### Platform Details

* Version of vCenter: 6.5
* Version of ESXi:6.5

### Scenario:

I would like to build the vm in vCenter and run ansible provisioner.

### Steps to Reproduce:

Using kitchen.yml with below config -

https://gist.github.com/riponbanik/fdb3d117d44ec02d1d01f6369b93ec26

### Expected Result:

Fix the issue. I can build vm in vcenter using Ansible/Terraform etc. using the same config for vcenter.

### Actual Result:

It gives the following error -

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [HTTP error (404)] on default-el7
D      ----------------------
D      ------Backtrace-------
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:183:in `report_errors'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:174:in `run_action'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/command/action.rb:36:in `block in call'
D      C:/Tools/ruby24/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/command/action.rb:34:in `call'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/cli.rb:52:in `perform'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/bin/kitchen:13:in `block in <top (required)>'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/bin/kitchen:13:in `<top (required)>'
D      C:/Tools/ruby24/bin/kitchen:22:in `load'
D      C:/Tools/ruby24/bin/kitchen:22:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [HTTP error (404)] on default-el7
D      ----------------------
D      ------Backtrace-------
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/savon-2.12.0/lib/savon/operation.rb:27:in `rescue in ensure_exists!'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/savon-2.12.0/lib/savon/operation.rb:22:in `ensure_exists!'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/savon-2.12.0/lib/savon/operation.rb:15:in `create'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/savon-2.12.0/lib/savon/client.rb:32:in `operation'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/savon-2.12.0/lib/savon/client.rb:36:in `call'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/kitchen-vcenter-1.2.1/lib/lookup_service_helper.rb:213:in `invoke'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/kitchen-vcenter-1.2.1/lib/lookup_service_helper.rb:170:in `find_service_url'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/kitchen-vcenter-1.2.1/lib/lookup_service_helper.rb:54:in `find_vapi_urls'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/kitchen-vcenter-1.2.1/lib/kitchen/driver/vcenter.rb:184:in `connect'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/kitchen-vcenter-1.2.1/lib/kitchen/driver/vcenter.rb:60:in `create'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:484:in `public_send'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:484:in `block in perform_action'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:551:in `synchronize_or_call'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:513:in `block in action'
D      C:/Tools/ruby24/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:512:in `action'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:484:in `perform_action'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:394:in `create_action'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:129:in `create'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `public_send'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      C:/Tools/ruby24/lib/ruby/gems/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [HTTP error (404)]

**Comment by tecracer-theinen** [comment]
Same just happened here. At least in our case it seems to be an issue in vCenter itself, tracing back to a problem with the LookupService of the installation.

On installations where the plugin works, that URL returns a 500 (of course, as I did not send a proper SOAP query). On the problematic system, it returns 404.

Working system:
```
curl -ikX POST https://VCENTER/lookupservice/sdk
HTTP/1.1 500
...
```

Non-Working system:
```
curl -ikX POST https://VCENTER/lookupservice/sdk
HTTP/1.1 404 Not Found
...
```

Could you check, if this is the same case? Then, it's a vCenter-side issue

**Comment by riponbanik** [comment]
@tecracer-theinen  Thanks I get 404 error when using curl, when use browser I see the following error -

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Body>
<soapenv:Fault>
<faultcode>ServerFaultCode</faultcode>
<faultstring>
Unexpected EOF in prolog at [row,col {unknown-source}]: [1,0]
</faultstring>
<detail>
<RuntimeFaultFault xmlns="urn:vim25" xmlns:vim25="urn:vim25" xsi:type="vim25:InvalidRequest"/>
</detail>
</soapenv:Fault>
</soapenv:Body>
</soapenv:Envelope>

**Comment by tecracer-theinen** [comment]
I suppose the output you see in the browser is just the vCenter API complaining about an invalid request, as it's not made for browser access.

The customer project where I had the same issue has still to resolve this. I'll try to keep this issue updated with any info I get.
