### ISSUE TITLE
Message: Could not load the 'vcenter' driver from the load path.

### ISSUE THREAD

**Issue by rayabueg** [chef/kitchen-vcenter#5]
### Versions:

* Version of kitchen-vcenter: 1.0.0
* Version of test-kitchen: 1.17.0
* Version of chef: 13.2.20

### Platform Details

* Version of vCenter: Version 6.5.0.10000 Build 5973321
* Version of ESXi: VMware ESXi, 6.5.0, 4887370

### Scenario:

Ran instructions to install chef gem, updated .kitchen.yml accordingly, but get the following then running kitchen list:

kitchen list
**>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'vcenter' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration**

### Steps to Reproduce:

chef gem install kitchen-vcenter
update .kitchen.yml for environment
kitchen list
### Expected Result:

list kitchen vm's
### Actual Result:

**>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'vcenter' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration**

**Comment by jjasghar** [comment]
Can you try `chef exec kitchen list`?

**Comment by rayabueg** [comment]
Same error:

chef exec kitchen list
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'vcenter' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by jjasghar** [comment]
Can you check this location? Are there two directories here?

```
~/.chefdk/gem/ruby > ls
2.3.0/
~/.chefdk/gem/ruby >
```

**Comment by rayabueg** [comment]
Hmm…only have ~/.chefdk/gem/ruby/2.4.0

**Comment by Defilan** [comment]
Hi JJ,

We are still having this issue. I even tried this a few minutes ago on a brand new, non-configured Ubuntu 16.04 box with a fresh ChefDK install. This is the error I get following the instructions on the README (install the sdk and kitchen-vcenter gems):

<img width="1462" alt="screen shot 2017-09-18 at 10 43 38 am" src="https://user-images.githubusercontent.com/7034124/30556057-694cb434-9c5e-11e7-89d9-90ce3a9a0cf9.png">

Any ideas?

Thanks for your help!

-Chris (Defilan)

**Comment by jjasghar** [comment]
Yep, we figured it out. Can you ping me in slack and i can walk you through it.

**Comment by jjasghar** [comment]
Declaring the `/opt/chefdk/embedded/bin/kitchen list` for the ChefDK should be a workaround. https://github.com/chef/appbundler/issues/33 is the issue that will resolve this issue too.
