### ISSUE TITLE
`wait_for_retry` parameter ignored

### ISSUE THREAD

**Issue by dry4ng** [chef/kitchen-vcenter#67]
I'm setting `wait_for_retry` to 180 seconds, but it's being ignored, and default value of 90 seconds is being used. The Windows VM acquires IP successfully, a little over 90 seconds, but kitchen exits with an error.

```
kitchen create
-----> Starting Kitchen (v1.24.0)
-----> Creating <default-Win2016>...
       Assigning network VL2...
       Cloning 'Templates/Windows_Server_2016' to create the VM...
       Waiting for reconfiguration to finish
       Waiting for VMware tools/network interfaces to become available (timeout: 90 seconds)...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [No valid IP found on VM ] on default-Win2016
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by tecracer-theinen** [comment]
If I see it correctly, the mentioned `wait_for_retry` parameter is a provisioner level setting (e.g. Chef provisioner), while this driver is running at an earlier stage. Please try the `vm_wait_timeout` parameter in the `driver` section of your kitchen.yml and give me some feedback if that worked?

Basically the order of plugins triggered is "driver -> transport/provisioner -> verifier" where each stage is separate - hence the different settings.

**Comment by dry4ng** [comment]
Setting `vm_wait_timeout` does change the message, but it's still failing.
According to Vcenter, the VM first acquires IP from 169 range, and then a minute later it gets proper IP from DHCP. But Kitchen already failed at that point.

**Comment by marcparadise** [comment]
@dry4ng thanks for posting this - I know it's been a while, but is this an issue you're still seeing in more recent versions of `kitchen-vcenter`?

**Comment by vkarve-chef** [comment]
hi @dry4ng we are closing this one for now. please feel free to reopen if the issue still exists in the newer version of kitchen-vcenter.
