### ISSUE TITLE
Guest Customization

### ISSUE THREAD

**Issue by donwlewis** [chef/kitchen-vcenter#69]
### Describe the Enhancement:
Ability to do Guest Customization

### Describe the Need:
It would be nice to be able to customize the guest virtual machine.  I specifically am looking for setting the hostname of the system, but I know configuring things like IP and such would be helpful as well.

### Current Alternative
Currently I have to create the machine and the login and set the hostname manually.

**Comment by Belogix** [comment]
I am addressing this and I am hoping to raise a PR in a couple of weeks if that helps! I should add though that it will introduce a few breaking changes so may or may not be accepted. If it isn't then I will provide instructions for others to patch the gem with the fixes (copy files) to at least unblock others.

**Comment by mkennedy85** [comment]
@donwlewis this has been enabled in the gem and will be released in the next Chef Workstation release. I will keep an eye out for any issues or additional feature requests.

**Comment by clintoncwolfe** [comment]
I believe with pr #124 adding windows support we now have guest customization support in v2.9.0.
