### ISSUE TITLE
Needs to incorporate the features of the kitchen-vsphere driver in the chef-provisioning-vsphere gem

### ISSUE THREAD

**Issue by lamont-granquist** [chef/kitchen-vcenter#81]
The chef-provisioning-vsphere gem was deprecated due to chef-provisioning being deprecated.  That gem however had a
vsphere kitchen driver embedded in it:

https://github.com/chef-boneyard/chef-provisioning-vsphere/blob/master/lib/kitchen/driver/vsphere.rb

Users tend to prefer that driver over this driver due to the feature set.  That driver is dead though so the path forwards would be to port its features into this gem.

I have no idea which features are necessary to do this, and have zero time and zero experience experience with vmware/vcenter/vsphere to actually be able to do this, but we need a tracking ticket somewhere for it.

Users should post the features they need here, or links to other issues.

**Comment by cattywampus** [comment]
I tried to use this plugin with our customer and ran into some issues with the lack of feature parity between this and the deprecated `chef-provisioningvsphere` plugin. Here's our wish list:

* Support attaching the VM to multiple networks
* Use the linux customization to set the DNS name server
* Use the linux customization to set the hostname and domain

**Comment by Belogix** [comment]
I am addressing some (not all) of these issues as we have the same issues. I am hoping to raise a PR in a couple of weeks if that helps!

**Comment by jimbodragon** [comment]
It would be very appreciate if we could change the Datastore at least like chef-provisioning-vsphere do by assign to a specific datastore. The cluster datastore could be set later.

**Comment by marcparadise** [comment]
It looks like #124 has addressed customizing DNS name server, hostname and domain; but I don't see that it allows for customization of datastore or attaching to multiple networks.  @cattywampus, @belogix are you aware of any separate work that was done on that front? 

If not, I am thinking it would be best to open these as two separate issues in this repository and close out this original request on the basis of work done in #124.

**Comment by cattywampus** [comment]
@marcparadise understood. I created a new issue for the multiple network piece.

**Comment by vkarve-chef** [comment]
closing based on above comment.
