### ISSUE TITLE
kitchen login always prompting for password

### ISSUE THREAD

**Issue by donwlewis** [chef/kitchen-vcenter#86]
### Versions:
2.6.2

### Platform Details
vCenter 6.5.0 Build 9451637

### Scenario:
Kitchen login is always prompting for password.

### Steps to Reproduce:
- Create a VM with the default vagrant username and password.
- Run kitchen create to create the instance
- Run kitchen login.  You will be prompted for password

### Expected Result:
Login without password prompt.

### Actual Result:
Prompted for password

This seems to be the case whether using the default, using `transport` `username` and `password` options, or using the `vm_name` and vm_password` options for the driver.

**Comment by tecracer-theinen** [comment]
As discussed on Slack, this is a limitation of the kitchen-ssh transport and not a kitchen-vcenter issue. The SSH transport simply does not set the password flag, but relies on manual input of the password or SSH keys instead.

There has been a lengthy discussion on https://github.com/test-kitchen/test-kitchen/issues/1461 and it looks like it's not going to be implemented.
