### ISSUE TITLE
kitchen-vcenter testing failure on windows caused by ffi update to 1.13

### ISSUE THREAD

**Issue by sean-horn** [chef/kitchen-vcenter#94]
### Versions:

* Version of kitchen-vcenter: 2.7.0
* Version of chef-workstation: 0.15.18
* Version of test-kitchen: 2.3.4
* Version of chef:  15.7.32

### Platform
* Windows

### Scenario:
The kitchen-vcenter gem at version 2.7.0 depends on the test-kitchen gem, which depends on the winrm gem, which depends on ffi. The 1.13 update of ffi is breaking chefspec runs needed for a CI system.

### Steps to Reproduce:
You can replicate this by installing ffi 1.13.0 on a windows system, opening irb, and running `require 'chefspec'` and you'll get an immediate crash.

### Expected Result:
kitchen-vcenter is able to work with ffi > 1.12

### Actual Result:
Crash upon requiring chefspec with ffi >= 1.13.0 in the dependency chain

### Additional context:
It looks like the issue with the updated ffi was fixed in the core workstation product, but has not been addressed for the kitchen-vcenter Gem.
See: https://github.com/chef/chef-workstation/commit/925e50af638bb6852096f567912204c7cc781e90 for the core workstation product.

**Comment by tas50** [comment]
@sean-horn Solving this in kitchen-vcenter or test-kitchen itself probably isn't the right place. If winrm depends on FFI then that's the place it should be addressed. Adding it here only adds another dependency we have to work around and cleanup later.
