### ISSUE TITLE
Failed to complete #create action: [Unable to find template: centos74-noGVTPL] on default-centos-7

### ISSUE THREAD

**Issue by dvenrao** [chef/kitchen-vcenter#95]
### Versions:

* Version of kitchen-vcenter: 2.7.0 
* Version of test-kitchen: 2.5.1
* Version of chef: 15.11.8
* Version of ChefDK: 4.8.23

### Platform Details

* Version of vCenter: 6.7.0
* Version of ESXi: 6.0.0 

### Scenario:
 kitchen create 
Vm templates existing in root directory of datacenter name Chef
In production we are using chef-provisioning-vsphere gem and creating new vms by test kitchen  but this is not compatible with chefdk4 so i want to shift to this gem

### Steps to Reproduce:
driver:
  name: vcenter
  vcenter_username: <%= ENV['VCENTER_USER'] %>
  vcenter_password: <%= ENV['VCENTER_PASSWORD'] %>
  vcenter_host:  <%= ENV['VCENTER_HOST'] %>
  datacenter: Chef
  folder: TESTKITCHEN
  vcenter_disable_ssl_verify: true
  template: centos74-noGVTPL

I don't see template issue , if i use https://github.com/chef/knife-vsphere gem
knife[:vsphere_user] = <%= ENV['VCENTER_USER'] %>
knife[:vsphere_pass] = <%= ENV['VCENTER_PASSWORD'] %>
knife[:vsphere_host] = <%= ENV['VCENTER_HOST'] %>
knife[:vsphere_insecure] = true # if you want to disable SSL checking
knife[:vsphere_dc] = "Chef"

# knife vsphere template list
Template Name: centos74-noGVTPL
Template Name: centos69-noGVTPL

### Expected Result:
create VM in vcenter

### Actual Result:
-----> Starting Test Kitchen (v2.5.1)
-----> Creating <default-centos-7>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Unable to find template: centos74-noGVTPL] on default-centos-7
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by dvenrao** [comment]
Issue is My datacenter 'Chef' exists at folder path  QClassic/Dedicated Environments/QCT/SW Eng/
If i give datacenter 'QClassic/Dedicated Environments/QCT/SW Eng/Chef' getting error Unable to find data center: QClassic/Dedicated Environments/QCT/SW Eng/Chef]

As per api document https://www.rubydoc.info/gems/mkuzmin-rbvmomi/1.8.2.1/RbVmomi/VIM/Folder:findByInventoryPath
“My Folder/My Datacenter/vm/Discovered VM/VM1”
Please Provide option to pass “My Folder" name for the above example method at
https://github.com/chef/kitchen-vcenter/blob/master/lib/support/clone_vm.rb#L439

**Comment by clintoncwolfe** [comment]
The error I receive when using a datacenter that is in a Folder is "Unable to find data center". I found that the API expects to lookup data centers without the folder, using the DC name as unique. So, I'm adding a line of code to disregard the folder if provided.

**Comment by dvenrao** [comment]
First I got error for 'Chef' datacenter without folder name , so then i tried this folder names.
I mean code is not finding unique datacenter names in vcenter, it works only if datacenter exists in root folder.

**Comment by clintoncwolfe** [comment]
Looks like the API can actually take a folder filter argument. I'll modify the call to pass the folder separately. 

https://www.rubydoc.info/gems/vsphere-automation-vcenter/0.4.6/VSphereAutomation/VCenter/DatacenterApi#list-instance_method
